os: osx
osx_image: xcode10.2
branches:
  only:
    - master

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=Owl.xcodeproj
  - IOS_FRAMEWORK_SCHEME="Owl-iOS"
  matrix:
    - DESTINATION="OS=12.2,name=iPhone X"          SCHEME="$IOS_FRAMEWORK_SCHEME"

script:
  # Ensures that the return code from xcodebuild is passed along to xcpretty
  - set -o pipefail
  
  # Runs the tests in Debug and Release configurations | xcpretty
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty